---
- name: Create Job Template for Remediation
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Job Template
      ansible.controller.job_template:
        name: "ðŸ”§âœ… SNOW Remediation Job Template"
        job_type: "run"
        inventory: "{{ input_inventory | default('lab-inventory') }}"
        project: "{{ input_project | default('Lightspeed-Playbooks') }}"
        playbook: "{{ workflow_inc_number | default('lightspeed-response') }}.yml"
        credential: "{{ input_credential | default('lab-credential') }}"
        validate_certs: true
        execution_environment: "Default execution environment"
        become_enabled: true
        ask_limit_on_launch: true
        ask_credential_on_launch: true

